"""Dependency-free CleanDrop domain."""

from cleandrop.domain.models import (
    CheckStatus,
    Finding,
    FindingKind,
    FindingSource,
    InspectionReport,
    JobReport,
    JobState,
    MediaType,
    NormalizedRect,
    RedactionRegion,
    ResourceLimits,
    SanitizationPlan,
    SanitizationProfile,
    Severity,
    VerificationCheck,
    VerificationResult,
    VerificationStatus,
)

__all__ = [
    "CheckStatus",
    "Finding",
    "FindingKind",
    "FindingSource",
    "InspectionReport",
    "JobReport",
    "JobState",
    "MediaType",
    "NormalizedRect",
    "RedactionRegion",
    "ResourceLimits",
    "SanitizationPlan",
    "SanitizationProfile",
    "Severity",
    "VerificationCheck",
    "VerificationResult",
    "VerificationStatus",
]
